### PR TITLE
Enqueue `block-editor.js` dependencies that I didn't enqueue before

### LINKED ISSUE #168: missing dependencies on wordpress 6.4
## Bug summary

On wordpress 6.4 our custom blocks based on genesis are no longer displayed in the editor. 

1. The first issues is that [wordpress dropped lodash](https://github.com/WordPress/gutenberg/pull/52571) but genesis seems to need it, possibly without properly requesting it.
2. The second issue is: `TypeError: undefined is not an object (evaluating 'rn.debounce')`.

The first issues can be quickfixed by explicitly loading lodash for example a script which is loaded in the editor. We are currently still looking for quickfixes for the second issue.

## Steps to reproduce

1. Update wordpress to 6.4
2. Check genesis custom blocks in the editor
3. check the browser console for errors

## Expected behavior
The Plugin should properly work with all stable version of wordpress.
## Actual behavior
Multiple js errors. On the frontend side it still seems to work.

## JS Console

```
TypeError: undefined is not an object (evaluating 'rn.debounce')
value — block-editor.js:2:71662
Jr — react-dom.min.js:4273
Zr — react-dom.min.js:4254:94
Gr — react-dom.min.js:4227
(anonymous function) — react-dom.min.js:5027
xl — react-dom.min.js:5051
fl — react-dom.min.js:4630:82
Nn — react-dom.min.js:1856
(anonymous function) — react-dom.min.js:4462
```
## Suspected cause (optional)
It looks like a missing functions (debounce). Possibly it is due to a version conflict of react dom.

## Versions

 - WordPress version: 6.4
 - Genesis Custom Blocks version:  1.5.3 via wpmudev / 1.5.2 via github (both don't work, why is this discrepancy?)
 - OS: Mac
 - Browser: Safari
 - Device: MBP

### PR DESCRIPTION
**Pull request by kienstra**
## Changes
* Enqueue `block-editor.js` dependencies that I didn't enqueue before
* I actually didn't use [dist/block-editor.asset.php](https://plugins.trac.wordpress.org/browser/genesis-custom-blocks/trunk/js/dist/block-editor.asset.php?rev=2946749), nothing referenced that

Fixes #168

### CODE REVIEW

File: php/Blocks/Loader.php [hunk 1]
```diff
@@ -134,7 +134,7 @@ public function editor_assets() {
 		wp_enqueue_script(
 			$js_handle,
 			$this->assets['url']['entry'],
-			[],
```
Comment (kienstra) [inline php/Blocks/Loader.php:137]: I made the `dependencies` argument `[]` instead of `$js_config['dependencies']` in https://github.com/studiopress/genesis-custom-blocks/commit/c347a98b31a64b726cae0ed74733def0c203a6cb.

That was to prevent this PHP warning on `/wp-admin/widgets.php`:

```
Notice: Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.) in wp-includes/functions.php on line 6031
```

Comment (kienstra) [reply php/Blocks/Loader.php:137]: But that warning is less important now. 

Default themes like [Twenty Twentythree](https://github.com/wordpress/twentytwentythree) don't have widgets, and widgets are soft-deprecated in favor of site editing.

**Comment by kienstra** [comment]
CI/CD will pass once we merge https://github.com/studiopress/genesis-custom-blocks/pull/171

**Comment by johnstonphilip** [comment]
Replicated:
Screenshot 2023-11-09 at 11 48 03 AM

Fixed on this branch:
Screenshot 2023-11-09 at 11 48 20 AM

**Review by johnstonphilip — APPROVED** [review]

**Comment by kienstra** [comment]
Thanks so much, @johnstonphilip! Good to see your screenshots.
